# Generated by Django 4.0 on 2021-12-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='venue_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('Wifi', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('capecity', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('avalaible', models.CharField(max_length=50)),
                ('Discription', models.CharField(max_length=100)),
            ],
        ),
    ]
